### ISSUE TITLE
Issue 1 - what is this for

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/rio-stac#1]
Create STAC Item is still a problem, This repo aims to create a simple CLI/API to create stac item  from a raster dataset using Rasterio and PySTAC 

### Specs
- API should takes either a Rasterio dataset or a path
- We assume we cannot set all the properties

Wanted features:
- simple templates input to set default values
- get geometry from COG overviews? (to avoid fetching the full resolution data ?)

Optional features:
- support multi version?
- support POST output to an API?

```
rio stac my-tif.tif --version 0.0.9 -o item.json
```

ref: https://github.com/azavea/pystac/tree/HEAD/docs/tutorials/how-to-create-stac-catalogs.ipynb
```
{
    "type": "Feature",
    "stac_version": "0.8.1",
    "id": "local-image",
    "properties": {
        "datetime": "2019-11-05 16:43:22Z"
    },
    "geometry": {
        "type": "Polygon",
        "coordinates": [
            [
                [
                    37.6616853489879,
                    55.73478197572927
                ],
                [
                    37.6616853489879,
                    55.73882710285011
                ],
                [
                    37.66573047610874,
                    55.73882710285011
                ],
                [
                    37.66573047610874,
                    55.73478197572927
                ],
                [
                    37.6616853489879,
                    55.73478197572927
                ]
            ]
        ]
    },
    "bbox": [
        37.6616853489879,
        55.73478197572927,
        37.66573047610874,
        55.73882710285011
    ],
    "links": [
        {
            "rel": "root",
            "href": null,
            "type": "application/json"
        },
        {
            "rel": "parent",
            "href": null,
            "type": "application/json"
        }
    ],
    "assets": {
        "image": {
            "href": "/var/folders/sv/zr8j0t4j1f726nhlt3vb8c300000gn/T/tmpytmf1tsx/image.tif",
            "type": "image/vnd.stac.geotiff"
        }
    }
}
```

**Comment by vincentsarago** [comment]
### Refs
- https://github.com/sparkgeo/spotstac 👋  @jbants

**Comment by geospatial-jeff** [comment]
> * support multi version?

We should take into consideration that pystac currently only supports `0.8.0` and doesn't quite support `0.9.0` yet (https://github.com/azavea/pystac/issues/65)


> * support POST output to an API?

IMO this is outside the scope.  Especially if this will integrate will pystac which already provides its [own way](https://pystac.readthedocs.io/en/latest/concepts.html#using-stac-io) to define your write operations.  I also think limiting the scope to `image -> stac item` will make it easier to build on top of rio-stac.
