### ISSUE TITLE
Infer asset media type by default?

### ISSUE THREAD

**Issue by TomAugspurger** [developmentseed/rio-stac#26]
Looking at the source-code, I see that you can pass `asset_media_type="auto"` to infer the media type. Is there any reason not to use "auto" as the default? It seems reasonable to me to infer as much as possible from the file.

**Comment by vincentsarago** [comment]
👋 @TomAugspurger I can't exactly remember why in the API I choose to not default to auto. We could change that 👍

**Comment by TomAugspurger** [comment]
Cool, I'll make a PR!
