### ISSUE TITLE
null crs if rasterio can't convert it to epsg

### ISSUE THREAD

**Issue by clausmichele** [developmentseed/rio-stac#40]
Currently, if rasterio can't convert the CRS string to an EPSG code, rio-stac just sets the field to null:
https://github.com/developmentseed/rio-stac/blob/8e9932a2e950a56ec5b7be699069af0d7a9defcb/rio_stac/stac.py#L71
`proj:epsg: null`

it is fine to set epsg to null, since it's a required parameter, but we should provide either WKT2 or PROJJSON if EPSG is not available. Related issues:
https://github.com/stac-extensions/projection/issues/6
https://github.com/stac-extensions/projection/issues/7

I will provide a PR for getting a PROJJSON string if EPSG is null/None.

**Comment by vincentsarago** [comment]
closed by #41 🙏
